FastOBCPrunerForCausalLM:
  sparsity_distribution: uniform
  sparsity_type: unstructured
  is_module_pruner: true
  target_modules: .*(fc_(in|out)|(qkv|out)_proj)$
  prune_biases: false
  sequential: true
  block_size: 128
  damp: 1.0
  decoder_blocks: transformer.h
  pre_decoder_modules: ['transformer.wte']